config/routes.rb
Rails.application.routes.draw do
  # match errors to their templates
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  #Session routes
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  #Signup
  get    '/signup',  to: 'users#new'

  #Static pages
  get "/pages/:page", to: "pages#show"

  #Resources
  resources :users, only: [:create]

  resources :github_users, only: [:create]

  resources :teams, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :developers, only: [:show, :new, :create, :destroy, :edit, :update]
  end

  #get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'
  get '/paimages' => 'pages#paimages'

  #Root to landing page
  root to: "pages#show", page: "home"

  def query_params_to_query(request)
    query_params = request.params.except(:path, :format)
    query_params.any? ? "?#{query_params.to_query}" : ""
  end

  constraints(host: %r{^www.dev-stat.us}) do
    redirect_action = ->(params, _request) do
      "https://dev-stat.us/#{params[:path]}#{query_params_to_query(_request)}"
    end
    root to: redirect(redirect_action)
    match '/*path', to: redirect(redirect_action), via: [:get, :post]
  end
end

app/views/datapanels/medium/_add.html.erb
<div class="column is-6">
  <div class="box is-fullwidth datapanel medium">
    <header class="level">
    <div class="level-left">
      <p class="title is-5">
        <span class="icon has-medium-text"><i class="fa fa-medium"></i></span> Couldn't find <%= @developer.github_user.name %> on Medium, add his/her username below!
      </p>
    </div>
    <div class="level-right">
    </div>
    </header>
    <hr>

    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to edit_team_developer_path([@team, @developer]), class: "button is-secondary" do %>
          <span class="icon"><i class="fa fa-edit"></i></span><span>  Add</span>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/datapanels/medium/_publication.html.erb
<div class="box">
<article class="media">
  <figure class="media-left">
  </figure>
  <div class="media-content">
    <div class="content">
      <p>
        <strong><%= p[:title] %></strong>
        <br>
        <%= p[:subtitle] %>
      </p>
    </div>
    <nav class="level">
      <div class="level-left">
      </div>
    </nav>
  </div>
  <div class="media-right">

  </div>
</article>
</div>
<br>

app/views/datapanels/medium/_show.html.erb
<div class="column is-6">
  <div class="box is-fullwidth datapanel medium">
    <header class="level">
    <div class="level-left">
      <p class="">
        <span class="icon has-medium-text"><i class="fa fa-medium"></i></span> @<%= @developer.medium_username %>
      </p>
    </div>
    <div class="level-right">
    </div>
    </header>
    <hr>
    <nav class="level is-mobile">
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Posts</p>
          <p class="title">0</p>
        </div>
      </div>
    </nav>
    <% if false %>
      <% @recent_stories[:posts][0..4].each do |post| %>
        <%= render partial: 'datapanels/publication', locals: { :p => post } %>
      <% end %>
    <% end %>

    <div class="level">
      <div class="level-item has-text-centered">
        <a href="https://medium.com/@<%= @developer.username %>" target=_blank class="button is-primary is-outlined has-medium-text">Go to Medium Profile</a>
      </div>
    </div>
  </div>
</div>