config/routes.rb
Rails.application.routes.draw do
  # match errors to their templates
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  #Session routes
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  #Signup
  get    '/signup',  to: 'users#new'

  #Static pages
  get "/pages/:page", to: "pages#show"

  #Resources
  resources :users, only: [:create]

  resources :github_users, only: [:create]

  resources :teams, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :developers, only: [:show, :new, :create, :destroy, :edit, :update]
  end

  #get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'
  get '/paimages' => 'pages#paimages'

  #Root to landing page
  root to: "pages#show", page: "home"

  def query_params_to_query(request)
    query_params = request.params.except(:path, :format)
    query_params.any? ? "?#{query_params.to_query}" : ""
  end

  constraints(host: %r{^www.dev-stat.us}) do
    redirect_action = ->(params, _request) do
      "https://dev-stat.us/#{params[:path]}#{query_params_to_query(_request)}"
    end
    root to: redirect(redirect_action)
    match '/*path', to: redirect(redirect_action), via: [:get, :post]
  end
end

app/views/shared/_sidenav.html.erb
<aside class="column is-2 aside hero is-fullheight is-hidden-mobile" id="sidenav">
  <div class="sidenav">
    <div class="title is-4 has-text-centered">Dev Audit</div>
    <div class="menu">
      <% if logged_in? %>
        <p class="menu-label">Hey <%= user.name %></p>
        <ul class="menu-list">
          <li><%= link_to 'Logout', logout_path, method: :delete %></li>
        </ul>
        <p class="menu-label">Your Teams</p>
        <ul class="menu-list">
          <% user.teams.each do |team| %>
            <li><%= link_to team.name, team %></li>
          <% end %>
          <li><%= link_to 'Add a new Team', new_team_path %></li>
        </ul>
      <% else %>
        <p class="menu-label">Welcome back!</p>
          <ul class="menu-list">
          <li><%= link_to 'Login', login_path %></li>
        </ul>
        <p class="menu-label">New here?</p>
          <ul class="menu-list">
          <li><%= link_to 'Register', signup_path %></li>
        </ul>
      <% end %>
      <p class="menu-label">Some Public Teams</p>
      <ul class="menu-list">
        <% Team.where(is_public: true).limit(10).each do |team| %>
          <li><%= link_to team.name, team %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <%= render partial: 'shared/footer' %>
</aside>

app/views/shared/not_owner.html.erb
<div class="columns">
  <div class="column is-half is-offset-one-quarter">
    <div class="card is-fullwidth has-text-centered">
      <h1 class="title card-form-header">It looks like this team isn't yours.</h1>
      <div class="card-content has-text-centered">
        <h5>Are you logged in with the correct account?</h5>
        <br>
        <%= link_to "Back to your teams", root_path, class: "button is-primary is-outlined" %>
      </div>
    </div>
  </div>
</div>